In [2]:
import random
import torch
import torch.nn as nn
import torch.optim as optim
import torchtext

In [28]:

class Bilinear_Attention(nn.Module):
    def __init__(self, encoder_dim, decoder_dim):
        super(Bilinear_Attention, self).__init__()
        self.W = nn.Linear(decoder_dim, encoder_dim, bias = False)
        self.fc = nn.Linear(decoder_dim + encoder_dim, decoder_dim)
        
    def forward(self, encoder_out, decoders_hidden):
        new_hiddens = []

        for decoder_hidden in decoders_hidden:
            decoder_attn = self.W(decoder_hidden)
            score = torch.matmul(decoder_attn, encoder_out.transpose(1,2))
            att_weights = torch.softmax(score, dim = 1)
            att = torch.sum(torch.matmul(att_weights,encoder_out), dim = 1)
            new_hidden = torch.cat((decoder_hidden, att) , dim = 1)
            new_hidden = self.fc(new_hidden)
            new_hidden = torch.tanh(new_hidden)
            new_hiddens.append(new_hidden)
        return torch.stack(new_hiddens)
        


In [29]:
encoder_out = torch.ones(3,3,5)
dec_hid = torch.ones(2,3,5)
for dec in dec_hid:
    print(dec)
att = Bilinear_Attention(5,5)

print(att.forward(encoder_out, dec_hid))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[[-0.2786, -0.8589, -0.0024,  0.1165, -0.8878],
         [-0.2786, -0.8589, -0.0024,  0.1165, -0.8878],
         [-0.2786, -0.8589, -0.0024,  0.1165, -0.8878]],

        [[-0.2786, -0.8589, -0.0024,  0.1165, -0.8878],
         [-0.2786, -0.8589, -0.0024,  0.1165, -0.8878],
         [-0.2786, -0.8589, -0.0024,  0.1165, -0.8878]]],
       grad_fn=<StackBackward0>)
